let selectedImage=null, selectedFileName="", selectedSource="upload", stream=null;
const fileInput=document.getElementById("fileInput"), dropzone=document.getElementById("dropzone"), uploadPreview=document.getElementById("uploadPreview");
const video=document.getElementById("video"), canvas=document.getElementById("canvas"), captureBtn=document.getElementById("captureBtn"), closeCamera=document.getElementById("closeCamera"), openCamera=document.getElementById("openCamera"), capturePreview=document.getElementById("capturePreview"), analyzeBtn=document.getElementById("analyzeBtn"), qualityBox=document.getElementById("qualityBox");
function setImage(dataUrl,name,source="upload"){selectedImage=dataUrl;selectedFileName=name||"camera-capture.jpg";selectedSource=source;const img=`<img src="${dataUrl}" alt="Selected oral region image"><div class="preview-info"><span>${selectedFileName}</span><span>${Math.round((dataUrl.length*0.75)/1024)} KB</span></div>`;if(source==="camera"){capturePreview.innerHTML=img;capturePreview.classList.remove("hidden")}else{uploadPreview.innerHTML=img;uploadPreview.classList.remove("hidden")}analyzeBtn.disabled=false;checkQuality(dataUrl)}
fileInput.addEventListener("change",e=>{const f=e.target.files[0];if(f)loadFile(f)});
function loadFile(f){if(!/^image\/(jpeg|png|webp)$/.test(f.type)){toast("Unsupported image format.");return}if(f.size>8*1024*1024){toast("Image is larger than 8 MB.");return}const r=new FileReader();r.onload=()=>setImage(r.result,f.name,"upload");r.readAsDataURL(f)}
["dragenter","dragover"].forEach(ev=>dropzone.addEventListener(ev,e=>{e.preventDefault();dropzone.style.borderColor="#0aa3a2"}));["dragleave","drop"].forEach(ev=>dropzone.addEventListener(ev,e=>{e.preventDefault();dropzone.style.borderColor=""}));dropzone.addEventListener("drop",e=>{const f=e.dataTransfer.files[0];if(f)loadFile(f)});
async function openCam(){if(!navigator.mediaDevices?.getUserMedia){toast("Camera API is not supported by this browser.");return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;video.style.display="block";document.getElementById("cameraPlaceholder").style.display="none";document.querySelector(".camera-frame").style.display="block";captureBtn.disabled=false;closeCamera.disabled=false;openCamera.disabled=true;toast("Camera ready.")}catch(e){toast("Camera permission denied or camera unavailable.")}}
function stopCam(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}video.srcObject=null;video.style.display="none";document.getElementById("cameraPlaceholder").style.display="grid";document.querySelector(".camera-frame").style.display="none";captureBtn.disabled=true;closeCamera.disabled=true;openCamera.disabled=false}
openCamera.onclick=openCam;closeCamera.onclick=stopCam;
captureBtn.onclick=()=>{if(!video.videoWidth)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext("2d").drawImage(video,0,0);setImage(canvas.toDataURL("image/jpeg",.9),"camera-capture.jpg","camera");toast("Image captured.");stopCam()};
function checkQuality(dataUrl){const img=new Image();img.onload=()=>{const c=document.createElement("canvas"),ctx=c.getContext("2d");const w=Math.min(180,img.width),h=Math.max(1,Math.round(img.height*w/img.width));c.width=w;c.height=h;ctx.drawImage(img,0,0,w,h);const px=ctx.getImageData(0,0,w,h).data;let sum=0,variance=0;for(let i=0;i<px.length;i+=4){const v=.299*px[i]+.587*px[i+1]+.114*px[i+2];sum+=v}const avg=sum/(px.length/4);for(let i=0;i<px.length;i+=4){const v=.299*px[i]+.587*px[i+1]+.114*px[i+2];variance+=(v-avg)**2}variance/=px.length/4;const bad=img.width<320||img.height<240||avg<35||avg>245;qualityBox.className="quality "+(bad?"bad":"good");qualityBox.classList.remove("hidden");qualityBox.innerHTML=bad?`<h3>⚠ Image Quality Insufficient</h3><p>Use good lighting, keep the camera steady, make sure the area is visible, avoid strong shadows and take a close, focused photograph.</p>`:`<h3>✓ Basic Image Quality Acceptable</h3><p>${img.width} × ${img.height}px · Brightness ${Math.round(avg)}/255 · Basic blur indicator checked. This is not clinical image-quality validation.</p>`;selectedImage=dataUrl};img.src=dataUrl}
function runAnalysis(){if(!selectedImage){toast("Please select an image first.");return}const demo=new URLSearchParams(location.search).get("demo")||localStorage.getItem("bc-demo-case");const payload={image:selectedImage,name:selectedFileName,source:selectedSource,demo:demo||null,started:Date.now()};sessionStorage.setItem("bc-pending",JSON.stringify(payload));localStorage.removeItem("bc-demo-case");analyzeBtn.disabled=true;analyzeBtn.textContent="Analyzing…";const overlay=document.createElement("div");overlay.style.cssText="position:fixed;inset:0;background:rgba(8,25,38,.88);z-index:200;display:grid;place-items:center;color:white";overlay.innerHTML=`<div style="width:min(460px,90%);text-align:center"><div class="eyebrow" style="color:#69ded8">DEMO AI PIPELINE</div><h2 style="font-size:30px">Analyzing Image</h2><p id="procText">Uploading image…</p><div style="height:8px;background:#304455;border-radius:99px;overflow:hidden"><div id="procBar" style="height:100%;width:10%;background:#19b7b2;transition:width .5s"></div></div></div>`;document.body.appendChild(overlay);const steps=["Uploading image…","Checking image quality…","Processing image…","Extracting visual features…","Generating screening result…"];let i=0;const timer=setInterval(()=>{i++;document.getElementById("procText").textContent=steps[Math.min(i,steps.length-1)];document.getElementById("procBar").style.width=(20+i*20)+"%";if(i>=steps.length-1){clearInterval(timer);setTimeout(()=>location.href="results.html",650)}},500)}
analyzeBtn.onclick=runAnalysis;
const demoParam=new URLSearchParams(location.search).get("demo");if(demoParam){const demoImgs={low:"assets/healthy-demo.svg",high:"assets/suspicious-demo.svg",poor:"assets/poor-quality-demo.svg"};fetch(demoImgs[demoParam]).then(r=>r.text()).then(svg=>setImage("data:image/svg+xml;charset=utf-8,"+encodeURIComponent(svg),"fictional-"+demoParam+"-case.svg","upload")).catch(()=>{})}
